### ISSUE TITLE
Implement Granular Pod Usage Limits

### ISSUE THREAD

**Issue by kreynoldsf5** [f5devcentral/volt-demo-app#30]
We're bumping up against quota usage limitations within a single vk8s. We need to implement more granular control of container resource limits within our pods.

## In deployment.spec

```yaml
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
```

## With Workload flavors

See limits [here](https://www.volterra.io/docs/reference/vks-api-comp#resource-management-for-volterra-vk8s).
We could create our own flavor (under 'shared' namespace) and assign it. Note this endpoint is not covered in the TF provider.
